server:
  port: 8080 # 客户端端口

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/ # 服务端地址

spring:
  application:
#    name: service-8080 #客户端名称 在服务端可以看见
    name: service-all #客户端名称 当多个客户端名称相同时,则可进行负载均衡