server:
  port: 8092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8091/eureka/

spring:
  application:
    name: config-server
  cloud:
    config:
      # 配置仓库的分支 不知道为啥没用
      # label: master
      server:
        git:
          # 配置仓库git的地址
          uri: https://github.com/SylvanasXy/SpringCloudDemo-ConfigCenter/

          # 配置仓库的路径
          search-paths: config

          # 当git仓库为private时,且有username&password时则需要下面的配置,当为public仓库时,则无需指明username&password
          # username: your username
          # password: your password

