server:
  port: 8086

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SylvanasXy/SpringCloudDemo-ConfigCenter/
          search-paths: config
          default-label: master
      label: master

