server:
  port: 8084 #Feign 端口

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/ #Eureka 服务端地址

spring:
  application:
    name: service-feign #Feign 名称
  zipkin:
    base-url: http://localhost:8093 # zipkin 服务端地址

feign:
  hystrix:
    enabled: true   # 断路器默认关闭, 需手动打开