server:
  port: 8091

eureka:
  instance:
    host: localhost
  client:
    registerWithEureka: false # 设置该参数表示该模块是服务端
    fetchRegistry: false # 同上
    serviceUrl:
      # 配置中心EurekaServer服务端地址
      # 注意: 服务名必须是"eureka",否则client端启动会报错!!!
      defaultZone: http://${eureka.instance.host}:${server.port}/eureka